import type {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from 'next'

import Head from 'next/head'

import { Home } from '@templates'
import { prefetchCoins, useGetCoins } from 'features/coins'

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {
      dehydratedState: await prefetchCoins(),
    },
  }
}

const Index: NextPage<
  InferGetServerSidePropsType<typeof getServerSideProps>
> = () => {
  const { data, isLoading } = useGetCoins()

  return (
    <>
      <Head>
        <title>Crypto List</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Home data={data} isLoading={isLoading} />
    </>
  )
}

export default Index
