import type { NextPage } from 'next'

import Head from 'next/head'

import { Home } from '@templates'
import { useGetCoins } from 'features/coins/queries'

const Index: NextPage = () => {
  const { data, isLoading } = useGetCoins()

  return (
    <>
      <Head>
        <title>Crypto List</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Home data={data} isLoading={isLoading} />
    </>
  )
}

export default Index
