import { Container } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container as="main">
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </Container>
    </>
  )
}

export default Home
